# Project information
site_name: My Docs
site_description: 
site_author: wanghao
site_url: https://thewanghao.github.io/mydoc/
edit_uri:

# Repository
repo_name: 'thewanghao/mydoc'
repo_url: 'https://github.com/thewanghao/mydoc/'

# Copyright
copyright: "Copyright &copy; 2023 - 2024 hao Wang"


theme:
  name: material
  custom_dir: overrides
  palette:
    primary: 'deep purple'
    accent: 'deep purple'

  font:
    text: Noto Sans SC
    code: Roboto Mono

  features:
    - header.autohide
    - navigation.tracking
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.top
    - navigation.instant

  favicon: 'docs/img/favicon.ico'

  language: 'zh'


# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/thewanghao


#  disqus: 'thewanghao'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
      alternate_style: True

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'


# Google Analytics
#google_analytics:
#  - "UA-156919721-1"
#  - "auto"


plugins:
  - search:
      lang:
        -en
        -ja

nav:
  - 我的笔记:
      - 1.介绍: index.md
      - 2.配置 YAML 文件: 配置 YAML 文件.md
      - 3.添加giscus: Comment with Giscus.md
      - 4.Reference: Reference.md
